### ISSUE TITLE
Very Good at Documentation

### ISSUE THREAD

**Issue by EMREOYUN** [w0rthy/SortingVisualizer#3]
No Compile Guides.
No Releases(Already Compiled App).
Missing Files to compile for people can know compiling.

@w0rthy we will waiting you.

**Comment by w0rthy** [comment]
I am completely aware of what I have and have not provided at this point.

**Comment by EMREOYUN** [comment]
That means getting the app is useless, only code viewing. Thanks for answering.

**Comment by ProjectHSI** [comment]
Sorry. I don't think that's correct.
*Ahem*
*Putting the folder into a C++ Project in Visual Studio allows the app to launch and compile. Just the GL/Glew.h(?) Files are missing preventing the app from running. And that's what the program complains about.*
Sorry to break your theroy @EMREOYUN .

**Comment by EMREOYUN** [comment]
I already left there btw.

**Comment by obipoketbobo** [comment]
> Sorry. I don't think that's correct.
> _Ahem_
> _Putting the folder into a C++ Project in Visual Studio allows the app to launch and compile. Just the GL/Glew.h(?) Files are missing preventing the app from running. And that's what the program complains about._
> Sorry to break your theroy @EMREOYUN .

there's still errors in the code after all dependencies have been added

**Comment by ProjectHSI** [comment]
Yeah.
